version: '3.8'

services:
  web:
    build: .
    container_name: django
    command: > 
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
