# Generated by Django 3.2.6 on 2022-02-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dot_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='description',
            field=models.TextField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='dot',
            name='rating',
            field=models.FloatField(blank=True),
        ),
    ]
