# Generated by Django 3.2.6 on 2022-02-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220202_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
