# Generated by Django 3.2.6 on 2022-02-05 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_dot_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dot',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
