# Generated by Django 3.2.6 on 2022-08-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dot_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dot',
            new_name='DotPrivate',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagPrivate',
        ),
    ]
