# Generated by Django 3.2.6 on 2022-08-16 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_tags_dotprivate_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dotprivate',
            old_name='tag',
            new_name='tags',
        ),
    ]
