# Generated by Django 3.2.6 on 2022-08-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_tag_dotprivate_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dotprivate',
            name='tags',
        ),
        migrations.AddField(
            model_name='dotprivate',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='core.tagprivate'),
        ),
    ]
